### ISSUE TITLE
Incorrect font color in code blocks without specified language

### ISSUE THREAD

**Issue by Nomango** [satnaing/astro-paper#162]
For example

```markdown
` ` `
some plain text
` ` `
```

The plain text is rendered into `color: var(--color-text-base)` which is a dark color in light theme. And the `one-dark-pro` highlight has a dark background color too.

Hope to get a solution, really like this theme :)

**Comment by shuaixr** [comment]
I have the same problem. According to my investigation, it is caused by Tailwind's prose affecting the theme of code blocks. 
```
.prose :is(:where(code):not(:where([class~="not-prose"],[class~="not-prose"] *))) {
    border-radius: 0.25rem;
    background-color: rgba(var(--color-card), var(--tw-bg-opacity));
    --tw-bg-opacity: 0.75;
    padding: 0.25rem;
    --tw-text-opacity: 1 !important;
    color: rgba(var(--color-text-base), var(--tw-text-opacity)) !important; 
}
```
I found many similar issues on Google but there don't seem to be good solutions.
[Feature Request: Disable the prose classes per element. #32](https://github.com/tailwindlabs/tailwindcss-typography/issues/32)
[Tailwind, prose, markdown - code samples show the: ` character](https://discourse.gohugo.io/t/tailwind-prose-markdown-code-samples-show-the-character/36106)

**Comment by shuaixr** [comment]
I solved the problem by removing the exclamation marks in lines 62 and 64 of `src/styles/base.css` for `prose-code:!text-skin-base` and `prose-pre:!text-skin-base`.

**Comment by Nomango** [comment]
Yes, removing `prose-pre:!text-skin-base` solves it!

But `prose-code:!text-skin-base` is necessary for \<code\> tag in dark theme.

**Comment by satnaing** [comment]
Thanks for pointing this out @Nomango 
Your PR #163 seems to be solving this issue.
But I have found another solution for this problem. 
We can solve this issue by only using css. 

Instead of removing `prose-code:!text-skin-base` from base.css
We can add another style targeting the white theme like this

_file: src/styles/base.css_

```css
  .prose {
    /* prose styles */
  }
  html[data-theme="light"] code span.line span:not([style]) {
    @apply text-skin-base invert;
  }
```

This solution also seems to be working. 
But there may be some edge cases I've missed.
