### ISSUE TITLE
Render tag name without slug when title

### ISSUE THREAD

**Issue by djmtype** [satnaing/astro-paper#179]
When a tag contains more than one word it is slugified. (Yay!) However, this means the page title and meta title render with the hyphen too. (Nay!) 
Maybe this is personal preference, but at least the H1 should be unslugified.

**Comment by Because789** [comment]
I'm trying to rework this part of the code at the moment anyway, but it seems that I'm not able to reproduce your issue. Could you show me an example, where this happens?

**Comment by djmtype** [comment]
Again, there's nothing technically wrong, more of a question. Would the h1 and meta title be better served as capitalized, and without being hyphenated?
![Screenshot 2023-12-18 at 11 11 03 AM](https://github.com/satnaing/astro-paper/assets/930713/52ba4bbe-c2f5-4cd6-8f34-9b6dedeff54a)

**Comment by Because789** [comment]
Ah, now I get it. I guess you could be right that in the end it boils down to personal taste. On the other hand, if you allow capitalized tags with spaces, why not show the original? One could argue, either allow and show them, or don't allow them. 

The thing is, with how the tags pages are implemented now, I believe the change wouldn't be as trivial as one might think.

**Comment by djmtype** [comment]
> The thing is, with how the tags pages are implemented now, I believe the change wouldn't be as trivial as one might think.

I'm curious, what do you mean?

**Comment by Because789** [comment]
Because all of these files play somehow a role in it:

https://github.com/satnaing/astro-paper/blob/main/src/pages/tags/%5Btag%5D.astro
https://github.com/satnaing/astro-paper/blob/main/src/pages/tags/index.astro
https://github.com/satnaing/astro-paper/blob/main/src/layouts/PostDetails.astro
https://github.com/satnaing/astro-paper/blob/main/src/components/Tag.astro
https://github.com/satnaing/astro-paper/blob/main/src/utils/getPostsByTag.ts
https://github.com/satnaing/astro-paper/blob/main/src/utils/getUniqueTags.ts
https://github.com/satnaing/astro-paper/blob/main/src/utils/slugify.ts

Maybe one could simply change the function getUniqueTags.ts to return the altered AND unaltered tag, and pass the unaltered tag to props in [tag].astro. But that might break other stuff, no idea.

**Comment by satnaing** [comment]
Hello @djmtype.
Thanks for pointing this out. I just made a PR for this and you can also check the preview URL [here](https://feat-unslugified-tag-titles.astro-paper.pages.dev/tags/).
