### ISSUE TITLE
Redirect page on google

### ISSUE THREAD

**Issue by eerison** [satnaing/astro-paper#196]
I saw that pages are generated without "/" on the end.
But when I access without it, it is redirecting the page, like

`/tags` redirects to `/tags/`

**Comment by satnaing** [comment]
Hello @eerison 
Maybe [this](https://docs.astro.build/en/reference/configuration-reference/#trailingslash) would help?

And also `trailing slash` redirects have to deal with the hosting provider like Netlify rather than AstroPaper. You can also check [Netlify's trailing-slash redirect option](https://docs.netlify.com/routing/redirects/redirect-options/#trailing-slash).

**Comment by satnaing** [comment]
This one has been stale for a while.
Thus, close this for now.
