### ISSUE TITLE
Tailwind MXD 

### ISSUE THREAD

**Issue by herediiaa** [satnaing/astro-paper#20]
Hello, how are you? I was looking at your theme to guide me on how to make mine and I hope you can help me with this question (it has nothing to do with your theme)
I have all the styles configured in tailwind and I left the layout of the posts for last and I don't know how to add styles to the markdown elements that I want to add, let's say that I want to put a h3(### example) (ONLY IN THE POST SECTION) green color, I have already been advised to do this "Remove the default tailwind base using this config option and add your own that includes the @layer and @apply directives" The problem is that when I configure this
"applyBaseStyles: false" removes ALL the styles that I set before and doesn't even show me the ones that I add with layer and apply, please help me, I'm waiting for your answer.

**Comment by satnaing** [comment]
Hello @herediiaa,

Normally, when it comes to styling markdown in TailwindCSS, [Tailwind's typography plugin](https://tailwindcss.com/docs/typography-plugin) is the way to go. Otherwise, we have to style every single element for each markdown element; and that'd be tedious.

However, we need to add some custom styles to certain elements when we don't like the default styles of Tailwind Typography plugin.
So, here is what I'd normally do.
```css
@layer base {
  /* other styles */
  .prose {
    @apply prose-h3:text-green-600;
  }
}
```
You can check how I did in AstroPaper by looking at `src/styles/base.css`.
Also, make sure to check out the [Typography plugin docs](https://tailwindcss.com/docs/typography-plugin#installation) to know more about adding custom styles.

**Comment by herediiaa** [comment]
Thanks for your answer man I will try

**Comment by satnaing** [comment]
I'll close this issue for now. You can reach out to me further via email.
