### ISSUE TITLE
Recent posts is empty if all the current posts are marked as featured 

### ISSUE THREAD

**Issue by SSmale** [satnaing/astro-paper#204]
On my version of this ([Smale.Codes](https://smale.codes) there is only one post and it is featured. As such there is nothing in Recent and nothing to say 'no posts here' or similar.

![image](https://github.com/satnaing/astro-paper/assets/17761689/48a3d30c-9e87-4d14-b3e4-2c4c85b236b3)

**Comment by satnaing** [comment]
I intentionally filtered `Featured Posts` under `Recent Posts` section.
In this way, I can avoid redundant posts in the index.

Maybe the best way to deal with this problem is to hide `Recent` section if there's no blog post for that.
Alternative method to solve this issue is displaying all posts without filtering featured posts.

To do so, for now, you can remove the filter logic in `src/pages/index.astro`

```jsx
    <section id="recent-posts">
      <h2>Recent Posts</h2>
      <ul>
        {
          sortedPosts
            .filter(({ data }) => !data.featured) // 👈🏻 remove this 
            .map(
              ({ data, slug }, index) =>
                index < 4 && (
                  <Card
                    href={`/posts/${slug}`}
                    frontmatter={data}
                    secHeading={false}
                  />
                )
            )
        }
      </ul>
 ....
```

**Comment by SSmale** [comment]
understood, I wonder if there needs to be some smarter logic to see if it is going to be empty then populate it as a message saying 'there are no posts' will be a bit odd. 

something like, if there are posts and there is something after the filter, show that, if there are sortedPosts but nothing after the filter, remove the filter, and if there are no sorted posts, show 'no posts yet'

**Comment by satnaing** [comment]
Made a PR for this issue.
Believe it solve this issue with no trade-offs.
