### ISSUE TITLE
Change the layout in index.astro.

### ISSUE THREAD

**Issue by monitor14** [satnaing/astro-paper#259]
![image](https://github.com/satnaing/astro-paper/assets/9653182/3b769c24-27d6-45e2-a0e1-5958c975e232)

Hi ,developer ,I want to change  the layout of index.astro as above , I just a beginner of frontend learner ,  can give any tips about it ? I try  many idea but  can't implement.

**Comment by satnaing** [comment]
It's been a while since you opened this.
So, I'm not sure this has been solved yourself.

In case I have to create such layout, I would use `Flexbox` of CSS. (in this case TailwindCSS)

## Code

```jsx
<div class="flex flex-col gap-y-2 sm:flex-row sm:gap-x-6">
  <div class="mx-auto size-56 flex-none bg-cyan-300">SVG</div>
  <p>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi
    voluptates unde reiciendis labore. Alias nemo maiores assumenda
    voluptatibus sunt molestias eum, enim id dolorem autem quia incidunt
    deleniti a voluptate?
  </p>
</div>
```

## Result:

**_Mobile_**
<img width="320" alt="Screenshot 2024-08-04 at 3 02 12 PM" src="https://github.com/user-attachments/assets/0f21716f-ca34-4d08-9576-6983b0d44dd7">

**_Tablet & Web_**
<img width="843" alt="Screenshot 2024-08-04 at 3 01 34 PM" src="https://github.com/user-attachments/assets/716ca8d4-6ae8-4b64-97f7-acbfc673001a">

Closing this issue for now.
If you have any problems, feel free to open a new discussion.
Thanks for your understanding.
