### ISSUE TITLE
toggle-theme.js

### ISSUE THREAD

**Issue by No1ceTea** [satnaing/astro-paper#293]
Not an issue, but I want to know why the toggle-theme.js is in the public folder ?

**Comment by satnaing** [comment]
@No1ceTea 
This is to avoid flickering during initial loading.
This file has to be one of the first things to load during initial rendering so that users using dark-mode won't notice a white flash.

You can see this kind of issue in [GitHub docs](https://docs.github.com/en/get-started). 

https://github.com/user-attachments/assets/dd199c3c-c8d9-4748-bea4-f14d04710b17
