### ISSUE TITLE
Cms need to connect to cms

### ISSUE THREAD

**Issue by fazi-gondal** [satnaing/astro-paper#307]
Sir please connect astro paper with any open source or free cms 
And astro paper theme is used by a cms which is [pagescms]((https://pagescms.org/))

**Comment by No1ceTea** [comment]
You can use Vercel.com to deploy you're AstroPaper Template

**Comment by satnaing** [comment]
AstroPaper doesn't need to be connected to a CMS out of the box since this theme can be easily integrated with any git-based CMS with minimal configuration.

I have tried integrating with [DecapCMS](https://decapcms.org/docs/intro/) (formerly Netlify CMS) by following the documentation.

You can also explore [other Headless CMS](https://jamstack.org/headless-cms/) options.

I'm going to close this issue for now. 
However, if you have any problems integrating a CMS, feel free to open a new issue. ✌🏼
