### ISSUE TITLE
feature request: use Astros built-in pagination

### ISSUE THREAD

**Issue by DerTimonius** [satnaing/astro-paper#370]
## Description

First of all, thanks for this great template!

While the pagination in Astro Paper works, but it feels a bit complicated. Since Astro 4.12, there is a built-in [`paginate`](https://docs.astro.build/en/reference/api-reference/#paginate) helper that makes pagination easier and also easier to debug if there is an issue.

Implementing the new pagination and removing the current version appears to be pretty-straightforward

- [x] I'm willing to contribute to this project, if this is green-lit

**Comment by satnaing** [comment]
Before the `paginate` helper was introduced, I couldn't rely on Astro's pagination method because my file and directory structure differed from the standard Astro blog setup. As a result, I had to create my own solution. When `paginate` was released, I didn't try it since my current implementation works fine.

If using `paginate` won't affect the behavior of current pagination, feel free to go ahead and submit a PR.

Thanks.
