### ISSUE TITLE
Cloudflare integration with theme may be broken

### ISSUE THREAD

**Issue by mailman-2097** [satnaing/astro-paper#44]
I am getting a lot of errors when running the npm run build.

I tried the following options to triage the issue:

a. changed the node versions using nvm, but now pegged to latest v16.19.1 lts/gallium release
> I could not use v18 as cloudflare build fails with node 18.

b. Did a diff of all the changes from the original template and my current project, to rule out any disruptive changes.

The major change is the cloudflare integration and the changes in the package and package-lock files

Raised a support request with Astro team on discord. 
The theme works as expected; the original template has no issues with `npm run build` on lts/gallium

Cloudflare integration may be the issue.

[build.error.log](https://github.com/satnaing/astro-paper/files/10909572/build.error.log)

**Comment by satnaing** [comment]
Hello @mailman-2097 

If you're not having any advantages provided by SSR, it's recommended to host AstroPaper as a static site directly on [Cloudflare Pages](https://pages.cloudflare.com/) instead of using [@astro/cloudflare](https://docs.astro.build/en/guides/integrations-guide/cloudflare/) SSR adapter. In this way, you'll have all the features of AstroPaper such as automatic sitemap generation, dynamic OG image generation etc. 
This is because SSR has some limitations when it comes to dynamic endpoints. For more info, check [this issue](https://github.com/withastro/astro/issues/3682#issuecomment-1163305696).

However, if you only want to use SSR for some reason, you can do the following
1) Disable dynamic OG image generation.
At the moment, AstroPaper doesn't provide an option for disabling dynamic OG image generation feature yet. In order to do so, you can simply remove `src/pages/[ogTitle].svg.ts` file.
2) Define routes in [`customPages` of sitemap.](https://docs.astro.build/en/guides/integrations-guide/sitemap/#custompages)
This is not mandatory; but if you want your sitemap to be working properly, you can provide your routes inside `customPages` option.
```js
// astro.config.mjs
...
    sitemap({
      customPages: ['https://nishad-link.pages.dev//posts/post-1', 'https://nishad-link.pages.dev//posts/post-2']
    }),
```

Your build process should be working fine after these step.

Above methods resolve your problems hopefully. If you still have some problems, let me know.

**Comment by mailman-2097** [comment]
Hi @satnaing,

Many thanks for your response. Fortunately, I will close the issue. 
I realised today the Cloudflare integration was for SSR support, which is not something I need. So I just ripped it out. Build issue resolved.
This is my first Nodejs project, hence the problem was not obvious to me. SSR, SSG all so confusing 😕.
But many thanks for your support.

**Comment by mailman-2097** [comment]
Sure will do. Thank you for the note. 👍
