### ISSUE TITLE
"No parser could be inferred" error when i try to commit 

### ISSUE THREAD

**Issue by o-t-w** [satnaing/astro-paper#52]
In my public directory I have an image file called logosquare.png.
When I try to do a git commit I get the following error: 
```
Preparing lint-staged...
❯ Running tasks for staged files...
  ❯ package.json — 2 files
    ❯ * — 2 files
      ✖ prettier --plugin-search-dir=. --write [FAILED]
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...

✖ prettier --plugin-search-dir=. --write:
[error] No parser could be inferred for file: public/logosquare.png
src/content/blog/submitter-formdata.md 217ms
husky - pre-commit hook exited with code 1 (error)
```

Also it's not well documented how to add images for a blog post.

**Comment by o-t-w** [comment]
I am still getting this error 
![Screenshot 2023-04-01 at 15 09 33](https://user-images.githubusercontent.com/29547922/229294244-fa95498c-a9fd-4963-a38f-f1df16483d78.png)

**Comment by floatingpurr** [comment]
The error is triggered by Prettier that is following these rules:

https://github.com/satnaing/astro-paper/blob/08151881ccfdc447e65a0a4d28c3ce2bbb5e8e09/.prettierignore#L1-L13

Prettier is triggered upon commit by a pre-commit hook:
https://github.com/satnaing/astro-paper/blob/08151881ccfdc447e65a0a4d28c3ce2bbb5e8e09/.husky/pre-commit#L1-L4

A simple way to get rid of that, preserving the hook, is adding `*.png` to your `.prettierignore`.

**Comment by satnaing** [comment]
Hello,
First of all, sorry for being late to resolve this issue. I've been busy for some time and couldn't focus on my open-source projects for a while.

In AstroPaper, lint-staged is triggered whenever we try to commit. Lint-staged is then configured to format (with prettier) the staged files. The error occurs because lint-staged is trying to format the staged `logosquare.png` which is obviously not a file to get formatted.

To resolve this issue, we can try a few ways

### 1) Disable lint-staged for a while when committing

We can disable lint-staged for a while by commenting out `npx lint-staged` inside `.husky/pre-commit` file. This is the easiest workaround for this kind of issue_ though this is not the real solution.

```bash
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# npx lint-staged
```

### 2) Ignore `public` directory in prettier

We can ignore the entire `public` directory, where the new `logosquare.png` exists, in prettier. By doing so, this issue is resolves although other files like `toggle-theme.js` and other codes won't be formatted in the future. So, this approach is also not recommended.

### 3) Update lint-staged config in package.json file (**Recommended**)

We can format everything except images like png, jpg, webp etc in lint-staged config inside package.json. This should solve the similar problems like this in the future, and thus, this method is recommended.

Before
```json
  "lint-staged": {
    "*": [
      "prettier --plugin-search-dir=. --write"
    ]
  }
```

After
```json
  "lint-staged": {
    "!(*.{png,jpg,jpeg,webp})": [
      "prettier --plugin-search-dir=. --write"
    ]
  }
```

Hope this helps you in some way. I'll try to make a PR for this issue too. If you still have some problems, plz let me know. Thanks.
