### ISSUE TITLE
Search page doesn't work as expected

### ISSUE THREAD

**Issue by floatingpurr** [satnaing/astro-paper#56]
The search box does not return expected results. E.g. in https://astro-paper.pages.dev/search/:

## input: 'aa ' 

it returns:
 
<img width="785" alt="image" src="https://user-images.githubusercontent.com/14820600/230329799-b9b83bcb-4ce1-44aa-8e37-5cbe9686e398.png">

but there isn't an actual match

## input: 'configuration' 

it returns:

<img width="784" alt="image" src="https://user-images.githubusercontent.com/14820600/230330604-02d42c37-59d0-4130-8d8e-35c665405655.png">

but it doesn't return [this other article](https://astro-paper.pages.dev/posts/customizing-astropaper-theme-color-schemes/) although there is a match.

<img width="828" alt="image" src="https://user-images.githubusercontent.com/14820600/230330730-cc79ba83-a26a-4a77-bfce-00b5631314b8.png">

**Comment by abhinav1912** [comment]
Looking at the implementation, fuzzy search is being done on the post title and description. That probably explains both issues (no full body search + @haobinliang's code search).

**Comment by satnaing** [comment]
Hello
Sorry for my very late reply.
The search functionality of AstroPaper is not a full-text search. Instead, it's just like filtering for titles and descriptions of blog posts. 

However, it'd be inefficient and ineffective when we try to include the entire body of the blog posts in the fuzzy search. 
1) There might be some performance issues when the post body is very long and there are many posts to be searched.
2) Since the entire body is included in the fuzzy search, there will be a lot of search results for a keyword. And thus, users might not be able to search effectively.

For those reasons, I excluded the entire body in the search logic.
However, if you want to have full-text search functionality, I'd recommend connecting with a database (instead of current markdown-file-based blogging). By connecting to a database, you can make indexes to certain tables and have full-text search functionality. 
Alternatively, you can connect to a third-party service like [Algolia](https://www.algolia.com/)

If you have any other good solutions, please let me know. 
I'll close this issue for now, but if you have something else to do, you can reopen this or create a new issue in the future.

Thank you.

**Comment by floatingpurr** [comment]
Hi @satnaing, thank you for your exhaustive reply. I was trying to extend fuzzy search, but, as you pointed out, it's not a good idea. The fuzzyness of the serch looks a little bit counterintuitive to me. It returns unexpected results (e.g., see the 'aa ' case). I guess that it's the price you have to pay if you want to work with a fuzzy search fashion : )

Thank you.
