### ISSUE TITLE
Very nice template - how about adding support for multi-language?

### ISSUE THREAD

**Issue by tiptronic** [satnaing/astro-paper#57]
Subject says it all.

Thanks for creating this nice template

**Comment by satnaing** [comment]
Hello,
Sorry for my late response. 
I've decided not to include multi-language (or i18n) support out of the box in AstroPaper. This is because there are third-party packages (eg: [astro-i18n](https://astro-i18next.yassinedoghri.com/)) for that feature and users can integrate multi-lang support using those with ease. Besides, I want to make it as minimal and lightweight as possible for different users.

I believe this approach might be beneficial for AstroPaper's users who do not need multi-language support, as it can keep the package simple and focused on its primary functionality. However, of course, you can give suggestions or feedback for this approach.

Thanks ✌🏻

**Comment by eerison** [comment]
Hey @satnaing 

But can't it be lazy load? then it could be loaded just for users that want to keep the site multi language, if not maybe add some component that could be activate manually when we install [astro-i18n](https://astro-i18next.yassinedoghri.com/)
