### ISSUE TITLE
OG Img on the Edge

### ISSUE THREAD

**Issue by Dax911** [satnaing/astro-paper#58]
Love Satori great package from vercel and I was actually using the nofuss starter, but it doesn't support Astro v2. So off on the hunt to rebuild with upgradability in mind.  I was hoping to add the Vercel Edge integration to my project and use that with Satori. This repo looks like a great to start.

Would adding that be of interest of anyone? If I can get it sorted out? Tho this would be a vercel focused version idk if that is a problem.

**Comment by satnaing** [comment]
Hello, sorry for my late reply.
You can use Vercel integrations if you want. However, if I try to integrate Vercel integrations, this template might become vendor-specific. Since AstroPaper is aimed to be used for general purposes and without any vendor-specificity, I've decided to keep this without Vercel integrations.

If you want, you can create a version of AstroPaper that is specifically focused on integrating with Vercel; and if someone wants a Vercel-focused version, I can redirect them to your repo in the future.

**Comment by satnaing** [comment]
I'm closing this issue for now. 
If you have any other questions or suggestions in the future, don't hesitate to open a new one. Thank you!
