### ISSUE TITLE
WebSocket server error: Port is already in use

### ISSUE THREAD

**Issue by alec-c4** [satnaing/astro-paper#72]
Hi! 
Thanks a lot for your work! But I meet strange behavior for a new app - when I start the app, I see message `WebSocket server error: Port is already in use`. What's wrong?

It looks like there is a conflict between `astro check --watch` and `astro dev` - when I run those commands separately, I see no error message

**Comment by jvtrigueros** [comment]
I believe it's an issue in this [line](https://github.com/satnaing/astro-paper/blob/63f1e3200f17df7feadaf4719182ff3df1644900/package.json#L6)

```
    "dev": "astro check --watch & astro dev",
```

Instead of one ampersand(&) it should be two (&&)

```
    "dev": "astro check --watch && astro dev",
```

**Comment by Brodypen** [comment]
Hi, I looked into this a bit and this doesn't work on my end.
I found that this line of code was from this [blogpost](https://astro.build/blog/astro-210/#astro-check-watch)
From what I understand, the one ampersand symbol (&) will run the two commands in parallel in which they will use the same port.

I'll update this if I find any information that can get rid of error.

**Comment by satnaing** [comment]
I found the cause of this problem and it is related to the commit [4fe5084](https://github.com/satnaing/astro-paper/commit/4fe508462e488246b8391793a6a5a1a3d9ecf74c).
Turns out, for some reason, if I add site URL from `src/config.ts`, **_"Port is already in use"_** problem occurs. I'm not really sure why tho. It seems like there might be an unexpected interaction or conflict with the way the site URL is configured.

I'll make a commit to resolve this issue.

Thanks everyone. ✌🏻
