### ISSUE TITLE
Unable to commit without adding txt and svg to lint config

### ISSUE THREAD

**Issue by matterramun** [satnaing/astro-paper#79]
Currently unable to commit due to `husky - pre-commit hook exited with code 1 (error)`

When running npm run cz and walking through the process presented I get the following:

```
❯ Running tasks for staged files...
  ❯ package.json — 73 files
    ❯ !(*.{png,jpg,jpeg,webp}) — 71 files
      ✖ prettier --plugin-search-dir=. --write [FAILED]
↓ Skipped because of errors from tasks. [SKIPPED]
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...

✖ prettier --plugin-search-dir=. --write:
[error] No parser could be inferred for file: public/assets/dev.svg
[error] No parser could be inferred for file: public/assets/logo.svg
[error] No parser could be inferred for file: public/favicon.svg
[error] No parser could be inferred for file: public/robots.txt

...

husky - pre-commit hook exited with code 1 (error)
git exited with error code 1
```

Working around this issue by adding `txt,svg` to package.json lint-staged value like so...
```
  "lint-staged": {
    "!(*.{png,jpg,jpeg,webp,txt,svg})": [
      "prettier --plugin-search-dir=. --write"
    ]
  }
}
```

Not sure if this is the proper way to fix this issue or if I'm just working around it...

**Comment by satnaing** [comment]
Yes, your workaround can be considered as the correct way to fix this issue.

The problem is that I configure AstroPaper to run prettier on currently staged files when commit. I only exclude some image files for that option. In your case, I assume you have staged files such as txt/svg; and when you tried to commit, it will throw an error since prettier cannot format those files.

I'll make a PR by configuring lint-staged to format only specific file types.
