### ISSUE TITLE
Avoid files with underscore

### ISSUE THREAD

**Issue by OxMarco** [satnaing/astro-paper#8]
When using GitHub Pages, asset files like `_slug_.d7aeaf57.css` don't load, probably because of the name. It should be replaced by something like `slug_d7aeaf57.css` removing the dot and the initial underscore.

**Comment by satnaing** [comment]
Have you tried Github Pages deployment guide from the [Astro docs](https://docs.astro.build/en/guides/deploy/github/)?

I tried according to that guide and assets files (css/js) work fine. However, I need to update links as following.
```jsx
<a href="/posts"  class={activeNav === "posts" ? "active" : ""}>Posts</a> // original link
```
```jsx
<a href="/my-repo-name/posts"  class={activeNav === "posts" ? "active" : ""}>Posts</a> // updated link
```

**Comment by OxMarco** [comment]
I am using a custom URL so it doesn't apply. I tried changing names as mentioned above and it works now, so I am quite sure it is a problem of underscores

**Comment by OxMarco** [comment]
This is the repo https://github.com/Ithil-protocol/jobs/tree/gh-pages

**Comment by satnaing** [comment]
I checked your repo and had to figure out where asset files like `_slug_.d7aeaf57.css` locates.

I think you might be deploying your site on Github Pages using `branch` method instead of `Github Action` way.
Astro (and I) recommend deploying on Github Pages using `Github Action`. In this way, you can avoid this kind of name updates on every push. I checked you site a while ago and it was working fine until you push another commit to your repo.
![image](https://user-images.githubusercontent.com/53733092/202860925-03869bd5-7752-473f-a2dd-b161a3e85b44.png)

I've created a new branch [github-pages-example](https://github.com/satnaing/astro-paper/tree/github-pages-example) where you can check out my Github Action workflows.

Hope this helps ✌🏻

(PS. with Github Pages, even though I follow the same step by step guide as the docs says, I found that I still need to update my links manually. For instance, something like `"/posts"` => `"/astro-paper/posts"`. So, the easier way to deploy this site would be using [Netlify](https://www.netlify.com/) or [Vercel](https://vercel.com/) or [Cloudflare Pages](https://pages.cloudflare.com/))

**Comment by OxMarco** [comment]
Perfect, works now. Thanks!!
